#Controller to control robot arm joints
robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [waist_to_base, arm01_to_waist, arm02_to_arm01, arm03_to_arm02, gripperbase_arm03]

#Controller to control end effector joints
hand_ee_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [Mgripper_to_gripperbase, gripper_to_gripperbase]

#Controller to continuously publish joint states/positions
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
